---

- name: Provision a {{ application_name }} server
  hosts: all
  sudo: yes
  sudo_user: "{{ default_user }}"
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
    - setup_scripts: yes
    - db_password: "{{ db_passwd }}"
    - application_name: "{{ app_name }}"
    - dotfiles_name: "{{ dotname }}"
  vars_files:
    - env_vars/base
    - env_vars/local

  roles:
    - base
    - db
    - web
