---

- name: Provision a {{ application_name }} server
  hosts: all
  connection: local
  gather_facts: True
  sudo: yes
  sudo_user: "{{ default_user }}"
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
    - setup_scripts: yes
    - run_django_syncdb: yes
    - run_django_south_migration: yes
    - run_django_collectstatic: yes
    - db_password: "{{ db_passwd }}"
    - application_name: "{{ app_name }}"
    - dotfiles_name: "{{ dotname }}"
    - environment: "{{ env }}"
    - email_pass: "{{ mail_pass }}"
    - instance_type: t1.micro
    - security_group: "{{ security_group }}"
    - image: ami-4ceaed4d
    - region: us-east-1
    - keypair: "{{ keypair }}"
    - vpc_subnet_id: "{{ vpc }}"
    - assign_public_ip: yes

  vars_files:
    - env_vars/base
    - env_vars/local

  roles:
    - base
    - db
    - web
    - memcached
