---

- name: Provision a {{ application_name }} server
  hosts: all
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
    - setup_scripts: yes
    - application_name: "{{ app_name }}"
    - dotfiles_name: "{{ dotname }}"
    - localuser: "{{ lookup('ENV','USER') }}"

  vars_files:
    - env_vars/base
    - env_vars/local

  roles:
    - base
    - web
