---

- name: restart application
  become: yes
  supervisorctl: name={{ application_name }} state=restarted

- name: restart nginx
  become: yes
  service: name=nginx state=restarted enabled=yes

- name: reload nginx
  become: yes
  service: name=nginx state=reloaded
