---

- name: Install MySQL
  sudo: yes
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=installed
  with_items:
    - mysql-server
    - libmysqlclient-dev
  tags: packages

- name: Install MySQL Python Packages
  sudo: yes
  pip: name={{ item }} state=latest
  with_items:
    - MySQL-python

- name: Ensure the MySQL service is running
  sudo: yes
  service: name=mysql state=started enabled=yes

- name: Ensure database is created
  mysql_db: db={{ db_name }}
            state=present
            login_user=root
            login_password=''
  ignore_errors: yes
  tags: mysql

- name: Ensure user has access to the database
  mysql_user: name=root
              login_user=root
              login_password=''
              host=localhost
              password={{ db_password }}
              priv=*.*:ALL,GRANT
              state=present
  ignore_errors: yes
  tags: mysql
