---

- name: Install MySQL
  sudo: yes
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=installed
  with_items:
    - mysql-server
    - libmysqlclient-dev
  tags: packages

- name: Install MySQL Python Packages
  sudo: yes
  pip: name={{ item }} state=latest
  with_items:
    - MySQL-python

- name: Ensure the MySQL service is running
  sudo: yes
  service: name=mysql state=started enabled=yes
