---

- name: Change permisson on dotfiles
  become: yes
  file: path={{ dotname }}
        state=directory
        owner={{ default_user }}
        group={{ default_user }}
        recurse=yes

- name: Link dotfiles
  command: "{{ dotname }}/ubuntu-conf.sh"
  when: setup_scripts
  ignore_errors: yes

- name: Install Vundle
  command: "{{ dotname }}/vundle-install.sh"
  when: setup_scripts
  ignore_errors: yes

- name: Source .bashrc
  shell: executable=/bin/bash source .bashrc

- name: Copy Xvfb init
  become: yes
  copy: src=roles/web/files/
        dest=/etc/init.d
        owner=root
        group=root
        mode=770

- name: Add Xvfb service
  become: yes
  command: update-rc.d xvfb defaults

- name: Start Xvfb
  become: yes
  service: name=xvfb state=started

- name: Does the Google apt file exist?
  command: test -f "{{ apt_file }}"
  register: google_apt_exists
  ignore_errors: True

- name: Add Google Chrome key
  become: yes
  shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  when: google_apt_exists.rc == 1

- name: Add Google Chrome repo
  become: yes
  copy: content="deb http://dl.google.com/linux/chrome/deb/ stable main" dest={{apt_file}} owner=root group=root mode=644
  when: google_apt_exists.rc == 1

- name: Update apt cache
  become: yes
  apt: update_cache=yes
  when: google_apt_exists.rc == 1

- name: Install Google Chrome Browser
  become: yes
  apt: pkg=google-chrome-stable state=installed

- name: Install Google Chrome Driver
  become: yes
  unarchive: src=http://chromedriver.storage.googleapis.com/2.9/chromedriver_linux64.zip
             dest=/usr/bin
             copy=no
             owner={{ default_user }}
             group={{ default_user }}
             mode=755

- name: Copy main test folder
  unarchive: src=roles/web/files/pytest.zip dest=/home/{{ default_user }}

- name: Copy requirements file
  copy: src=roles/web/files/requirements.txt
        dest=/home/{{ default_user }}

- name: Install python packages
  become: yes
  pip: requirements=/home/{{ default_user }}/requirements.txt

- name: Copy test runner script
  copy: src=roles/web/files/test.sh
        dest=/home/{{ default_user }}

- name: Run selenium script
  command: sh /home/{{ default_user }}/test.sh
