---

- name: Change permisson on dotfiles
  sudo_user: root
  file: path={{ dotname }}
        state=directory
        owner={{ default_user }}
        group={{ default_user }}
        recurse=yes

- name: Link dotfiles
  command: "{{ dotname }}/ubuntu-conf.sh"
  when: setup_scripts
  ignore_errors: yes

- name: Install Vundle
  command: "{{ dotname }}/vundle-install.sh"
  when: setup_scripts
  ignore_errors: yes

- name: Source .bashrc
  shell: executable=/bin/bash source .bashrc

- name: Create static/media directories pt.1
  sudo_user: root
  file: path=/var/www state=directory
        owner={{ default_user }}
        group={{ serving_group }}

- name: Create static/media directories pt.2
  sudo_user: root
  file: path=/var/www/assets state=directory
        owner={{ default_user }}
        group={{ serving_group }}

- name: Create static/media directories pt.3
  sudo_user: root
  file: path=/var/www/assets/static state=directory
        owner={{ default_user }}
        group={{ serving_group }}

- name: Create static/media directories pt.4
  sudo_user: root
  file: path=/var/www/assets/media state=directory
        owner={{ default_user }}
        group={{ serving_group }}

- name: Compass compile
  shell: cd {{ project_path }}/compass
         && compass compile
