---

- name: Install virtualenvwrapper
  become: yes
  pip: name=virtualenvwrapper

- name: Source virtualenvwrapper
  shell: echo "source /usr/local/bin/virtualenvwrapper.sh" >> .bash_aliases
  shell: executable=/bin/bash source `which virtualenvwrapper.sh`

- name: Create the virtualenv
  shell: executable=/bin/bash source `which virtualenvwrapper.sh` && mkvirtualenv {{ application_name }}
  ignore_errors: yes

- name: Copy pip requirements file
  copy: src=roles/web/files/requirements.txt
        dest=/home/{{ default_user }}

- name: Install python requirements to virtualenv
  become: yes
  pip: requirements=/home/{{ default_user }}/requirements.txt virtualenv={{ application_name }}
