---

- name: Install rubygems package
  sudo_user: root
  action: apt pkg=rubygems state=installed

- name: Install Compass
  sudo_user: root
  action: command gem install compass
          creates=/usr/local/bin/compass
