---

- name: Change permisson on dotfiles
  sudo: yes
  file: path={{ dotname }}
        state=directory
        owner={{ default_user }}
        group={{ default_user }}
        recurse=yes

- name: Link dotfiles
  command: "{{ dotname }}/ubuntu-conf.sh"
  when: setup_scripts
  ignore_errors: yes

- name: Install Vundle
  command: "{{ dotname }}/vundle-install.sh"
  when: setup_scripts
  ignore_errors: yes

- name: Source .bashrc
  shell: executable=/bin/bash source .bashrc
