---

- name: Install Nginx
  sudo: yes
  apt: name=nginx update_cache={{ update_apt_cache }} state=installed
  tags: packages

- name: Enure that the Nginx service is stopped
  sudo: yes
  service: name=nginx state=stopped

- name: Create the Nginx configuration file
  sudo: yes
  template: src=nginx_site_config.j2
            dest=/etc/nginx/sites-available/{{ application_name }}
            backup=yes

- name: Ensure that the default site is disabled
  sudo: yes
  command: rm /etc/nginx/sites-enabled/default
           removes=/etc/nginx/sites-enabled/default

- name: Ensure that the application site is enabled
  sudo: yes
  command: ln -s /etc/nginx/sites-available/{{ application_name }}
           /etc/nginx/sites-enabled/{{ application_name }}
           creates=/etc/nginx/sites-enabled/{{ application_name }}

- name: restart nginx
  sudo: yes
  service: name=nginx state=restarted enabled=yes
