---

- name: Install python packages to project
  shell: . {{ virtualenv_path }}/bin/activate
         && cd {{ project_path }}
         && pip install -r requirements.txt

- name: Create Django settings file
  template: src=django_settings_config.j2
            dest={{ settings_root }}/{{ settings_dir }}/settings.py
            backup=yes

- name: Symlink settings file
  shell: cd {{ settings_root }}
         && ln -s {{ settings_path }}settings.py __init__.py
  ignore_errors: yes

- name: Compile CSS
  shell: cd {{ project_path }}/compass
         && sass --update --force sass:../static/css --sourcemap=none

- name: Run Django collectstatic
  shell: . {{ virtualenv_path }}/bin/activate
         && cd {{ project_path }}
         && python manage.py collectstatic --noinput
  when: run_django_collectstatic

- name: Run the Django syncdb command
  shell: . {{ virtualenv_path }}/bin/activate
         && cd {{ project_path }}
         && python manage.py syncdb --noinput
  when: run_django_syncdb

- name: Run Django South migrations
  shell: . {{ virtualenv_path }}/bin/activate
         && . {{ virtualenv_path }}/bin/postactivate
         && cd {{ project_path }}
         && python manage.py migrate --noinput
  when: run_django_south_migration

#- name: Run the Fab db_load command
#  shell: . {{ virtualenv_path }}/bin/activate
#         && . {{ virtualenv_path }}/bin/postactivate
#         && cd {{ application_path }}
#         && fab db_load
#  when: run_fab_db_load
#  tags: fabric
