---

- name: Setup Dotfiles
  git: repo={{ dot_files }}
       dest=/home/{{ default_user }}
  tags: git

#- name: Setup the Git repo
#  git: repo={{ git_repo }}
#       dest={{ project_path }}
#       accept_hostkey=yes
#  when: setup_git_repo
#  tags: git





