---

- name: Link and dotfiles
  shell: "{{ dotname }}/ubuntu-conf.sh"
  ignore_errors: yes

- name: Source virtualenvwrapper
  shell: echo "source /usr/local/bin/virtualenvwrapper.sh" >> .bash_aliases
  shell: executable=/bin/bash source `which virtualenvwrapper.sh`

- name: Source .bashrc
  shell: executable=/bin/bash source .bashrc

- name: Create static/media directories pt.1
  file: path=/var/www state=directory
        owner={{ default_user }}
        group={{ serving_group }}

- name: Create static/media directories pt.2
  file: path=/var/www/assets state=directory
        owner={{ default_user }}
        group={{ serving_group }}

- name: Create static/media directories pt.3
  file: path=/var/www/assets/static state=directory
        owner={{ default_user }}
        group={{ serving_group }}

- name: Create static/media directories pt.4
  file: path=/var/www/assets/media state=directory
        owner={{ default_user }}
        group={{ serving_group }}
