- name: Provision an EC2 node
  action:
    module: ec2
      instance_tags="Ansible"
      group={{ security_group }}
      instance_type={{ instance_type }}
      image={{ image }}
      wait=true
      region={{ region }}
      keypair={{ keypair }}
      vpc_subnet_id={{ vpc_subnet_id }}
    register: ec2
  tags: provisioning

- name: Add new instance to host group
    local_action: add_host hostname={{ item.public_ip }}
      groupname=launched
    with_items: ec2.instances
  tags: provisioning

- name: Wait for SSH to come up
    wait_for:
      host={{ item.public_dns_name }}
      port=22
      delay=60
      timeout=320
      state=started
    with_items: ec2.instances
  tags: provisioning
