- name: Provision an EC2 node
  ec2:
    instance_tags="Ansible"
    group={{ security_group }}
    instance_type={{ instance_type }}
    image={{ image }}
    wait=true
    region={{ region }}
    keypair={{ keypair }}
    vpc_subnet_id={{ vpc_subnet_id }}
  register: ec2
  tags: provisioning

- name: Add new instance to host group
    lineinfile: dest=/etc/hosts
      regexp={{ item.public_dns_name }}
      insertafter="[launched]"
      line="ansible_ssh_private_key_file=~/.keys/{{ keypair }}.pem"
    with_items: ec2.instances
  tags: provisioning

- name: Wait for SSH to come up
    wait_for host={{ item.public_dns_name }}
    port=22
    delay=60
    timeout=320
    state=started
    with_items: ec2.instances
  tags: provisioning
