---

# Application settings.
virtualenv_path: "/home/{{ default_user }}/.virtualenvs/{{ application_name }}"
project_path: "{{ application_name }}"
application_path: "{{ application_name }}/{{ application_name }}"

application_log_dir: "/var/log/nginx"
gunicorn_log_file: "/var/log/supervisor/{{ application_name }}.log"
gunicorn_err_file: "/var/log/supervisor/{{ application_name }}_err.log"

settings_root: "{{ application_path }}/settings/"
settings_path: "{{ settings_dir }}/"

# Gunicorn settings
gunicorn_user: "{{ application_name }}"
gunicorn_group: webapps

# Static & Media Settings
serving_user: "{{ application_name }}"
serving_group: www-data

# Nginx settings
nginx_http_port: 80
nginx_https_port: 443
nginx_access_log_file: "{{ application_log_dir }}/nginx_access.log"
nginx_error_log_file: "{{ application_log_dir }}/nginx_error.log"
