---

- name: Ubuntu apt-get update
  become: yes
  apt: update_cache=yes

- name: Ensure OpenSSl and libssl are the latest versions
  become: yes
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=latest
  with_items:
    - openssl
    - libssl-dev
    - libssl-doc
  tags: packages

- name: Install base packages
  become: yes
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - build-essential
    - xvfb
    - x11-xkb-utils
    - xfonts-100dpi
    - xfonts-75dpi
    - xfonts-scalable
    - xfonts-cyrillic
    - x11-apps
    - git
    - ntp
    - sqlite3
    - unzip
    - python-dev
    - python-pip
    - python-pycurl
    - libfreetype6-dev
    - libjpeg8-dev
    - liblcms1-dev
    - libpng12-dev
    - zlib1g-dev
    - libmemcached-dev
    - libsqlite3-dev
    - libev-dev
    - libevent-dev
    - libgmp3-dev
    - libxslt1-dev
    - libxml2-dev
    - emacs23-nox
    - emacs-goodies-el
    - auto-complete-el
    - ruby
  tags: packages

- name: Install virtualenv
  become: yes
  pip: name=virtualenv
  tags: packages
