---

- name: Ubuntu apt-get update
  sudo: yes
  apt: update_cache=yes

- name: Ubuntu dist upgrade
  sudo: yes
  apt: upgrade=dist

- name: Ensure OpenSSl and libssl are the latest versions
  sudo: yes
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=latest
  with_items:
    - openssl
    - libssl-dev
    - libssl-doc
  tags: packages

- name: Install base packages
  sudo: yes
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - build-essential
    - git
    - ntp
    - sqlite3
    - unzip
    - python-dev
    - python-pip
    - python-pycurl
    - supervisor
    - libfreetype6-dev
    - libjpeg8-dev
    - liblcms1-dev
    - libpng12-dev
    - zlib1g-dev
    - libmemcached-dev
    - libsqlite3-dev
    - libev-dev
    - libevent-dev
    - libgmp3-dev
    - libxslt1-dev
    - libxml2-dev
    - emacs23-nox
    - emacs-goodies-el
    - auto-complete-el
    - rabbitmq-server
    - pyflakes
    - ruby
  tags: packages

- name: Install Python Packages
  sudo: yes
  pip: name={{ item }} state=latest
  with_items:
    - pyflakes

- name: Install Memcached
  sudo: yes
  apt: name=memcached update_cache={{ update_apt_cache }} state=installed
  tags: packages

- name: Install virtualenv
  sudo: yes
  pip: name=virtualenv
  tags: packages

- name: Install rubygems package
  sudo: yes
  action: apt pkg=rubygems state=installed

- name: Install sass
  sudo: yes
  action: command gem install sass
          creates=/usr/local/bin/sass

- name: Install Compass
  sudo: yes
  action: command gem install compass
          creates=/usr/local/bin/compass
