---

- name: Create the Memcached configuration file
  sudo: yes
  template: src=memcached.conf.j2
            dest=/etc/memcached.conf
            mode=0644
            backup=yes
  notify:
    - restart memcached

- name: Ensure the Memcached service is running
  sudo: yes
  service: name=memcached state=started enabled=yes
